language: ruby
sudo: false
rvm:
  - 2.4.2
before_script:
  - export TZ=Australia/Melbourne
script:
  - bundle exec rake test
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 1b86e91107f8088b58ed7ff2a7586658ef26c5ba2799a27ae316c022cb435ccc
