markdown:
  options:
    auto_ids: false

generation:
  paginated_posts: true
  day_archives: false

date_formats:
  month: '%B %Y'

paths:
  posts: 'interviews'

layouts:
  posts: 'interviews'
  category: 'interviews'