markdown:
  options:
    auto_ids: false

generation:
  paginated_posts: true
  day_archives: false

date_formats:
  month: '%B %Y'

paths:
  posts: 'interviews'
  categories: 'interviews/categories'

layouts:
  posts: 'interviews'
  category: 'interviews'

pagination:
  per_page: 5

category_names:
  bsd: 'BSD'
  mac: 'Macintosh'